Remove Key Flow unused methods
stackitcloud/stackit-sdk-go pull request #327
Opened 2024-02-16 15:55 UTC by hcsa73

2024-02-16 16:44 UTC, joaopalet reviewed
LGTM, maybe would just highlight in the changelogs that this was not used anywhere in the module

2024-02-16 17:38 UTC, vicentepinto98 requested changes

2024-02-16 17:38 UTC, vicentepinto98 commented on core/clients/key_flow.go
> -// GetToken returns the token field
This method is used in the CLI for the keyFlow

2024-02-16 17:38 UTC, vicentepinto98 commented on core/clients/key_flow.go
> -// GetToken returns the token field
We can't remove it, unless we would export the `token` field. But in this case I think it's not worth it to make the breaking change. I'm not sure why I didn't just make the field public at that time (I thought I did :thinking: )

2024-02-19 08:29 UTC, vicentepinto98 approved these changes

2024-02-19 09:41 UTC, vicentepinto98 approved these changes

2024-02-19 11:08 UTC, merged